all: start

start: obj/EquationSolutionFunctions.o obj/UserInterface.o obj/QuadraticEquationSolver.o obj/SolverTests.o obj/MyASSerts.o
	g++ obj/EquationSolutionFunctions.o obj/UserInterface.o obj/QuadraticEquationSolver.o obj/SolverTests.o obj/MyASSerts.o -o quadratka

obj/EquationSolutionFunctions.o: src/EquationSolutionFunctions.cpp
	g++ -c src/EquationSolutionFunctions.cpp  -o obj/EquationSolutionFunctions.o

obj/UserInterface.o: src/UserInterface.cpp
	g++ -c src/UserInterface.cpp -o obj/UserInterface.o

obj/QuadraticEquationSolver.o: src/QuadraticEquationSolver.cpp
	g++ -c src/QuadraticEquationSolver.cpp -o obj/QuadraticEquationSolver.o

obj/SolverTests.o: src/SolverTests.cpp
	g++ -c src/SolverTests.cpp -o obj/SolverTests.o

obj/MyASSerts.o: src/MyASSerts.cpp
	g++ -c src/MyASSerts.cpp -o obj/MyASSerts.o
